name: Build RootFS
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir rootfs
          docker run --rm -v $PWD/rootfs:/tmp/rootfs archlinux bash -c "
            pacman -Syu --noconfirm &&
            pacman -S base plasma-mobile mesa networkmanager --noconfirm &&
            tar --exclude='/sys' --exclude='/proc' --exclude='/dev' --exclude='/run' -czf /tmp/rootfs/rootfs.tar.gz /
          "
      - uses: actions/upload-artifact@v4
        with:
          name: rootfs
          path: rootfs/rootfs.tar.gz
