name: Build DTB from DTS
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: sudo apt update && sudo apt install -y device-tree-compiler

      - run: mkdir -p dtb_output

      # Компилируем только файлы, содержащие "raphael" в имени
      - run: |
          for dts in $(find . -name "*raphael*.dts"); do
            echo "Компиляция $dts..."
            dtc -I dts -O dtb -o dtb_output/$(basename ${dts%.dts}.dtb) $dts
          done

      - uses: actions/upload-artifact@v4
        with:
          name: dtb-files
          path: dtb_output/*.dtb
