name: Build DTB for Raphael
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y device-tree-compiler
      - run: mkdir -p dtb_output
      - run: dtc -I dts -O dtb -o dtb_output/sm8150-xiaomi-raphael.dtb sm8150-xiaomi-raphael.dts
      - uses: actions/upload-artifact@v4
        with:
          name: dtb-files
          path: dtb_output/*.dtb
