name: Build ext4 Image from Google Drive
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install gdown
        run: pip install gdown

      - name: Download rootfs.tar.gz from Google Drive
        run: |
          FILE_ID="1PbNtIB8LbDpo_CZTVpIjOmiOsyJiK72h"
          gdown "https://drive.google.com/uc?id=${FILE_ID}" -O rootfs.tar.gz

      - name: Create ext4 image
        run: |
          mkdir -p image
          dd if=/dev/zero of=image/arch-rootfs.img bs=1M count=4096
          mkfs.ext4 image/arch-rootfs.img
          mkdir -p /tmp/image_mount
          sudo mount image/arch-rootfs.img /tmp/image_mount
          sudo tar --numeric-owner -xzf rootfs.tar.gz -C /tmp/image_mount
          sudo umount /tmp/image_mount

      - uses: actions/upload-artifact@v4
        with:
          name: arch-rootfs-image
          path: image/arch-rootfs.img
