name: Build Kernel
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu make flex bison bc kmod
      - run: chmod +x linux/scripts/*
      - run: cd linux && make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig
      - run: cd linux && make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- Image
      - run: cd linux && make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- dtbs
      - uses: actions/upload-artifact@v4
        with:
          name: kernel-files
          path: |
            linux/arch/arm64/boot/Image
            linux/arch/arm64/boot/dts/qcom/*raphael*.dtb
